### ISSUE TITLE
Not compatible with crystal latest

### ISSUE THREAD

**Issue by samueleaton** [nedpals/sharn#7]
Hey thanks for building this. I definitely wanted something more user friendly like npm/yarn. But it looks like one of the dependencies is not up to date. 

https://github.com/mosop/cli/issues/13

**Comment by nedpals** [comment]
I will try to look into this. I'm not sure if I'm gonna use the stdlib's
optionparser instead (the dependency optarg is just a wrapper to it) or fork
the cli shard.
